[package]
name = "fairplay"
version = "0.1.0"
edition = "2021"

[dependencies]
reciever = { path = "./src/reciever"}
server = { path = "./src/server"}
clap = { version = "4.2.1", features = ["derive"] }
