[package]
name = "mydns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
edition = "2021"
name = "mydns"
path = "src/main.rs"

[dependencies]
mdns-sd = "0.5.9"
libmdns = "0.7.3"
httparse = "1.8.0"
